# @package _global_

flow:
  sig_min: 0.001
  sampling: beta
  alpha: 1.5
  beta: 1.0
  num_inference_steps: 10

training:
  steps_per_epoch: 100000
  seed: 42
  dynamic_data_seed: True
  objective: ${objective}
  debug: False
  profile: False
  resume: False
  lr_scheduler: cosine
  lr_warmup_steps: 2000
  train_vlm: True
  train_depth: False
  resume_checkpoint_path:
  finetune_checkpoint_path:
  normalizer_path: /share_data/zengfanlian/Projects/EgoVLA/outputs/normalizer/2026.03.16-relative-mixed/normalizer.pkl
  max_train_steps: null
  max_eval_steps: null
  num_epochs: 2
  use_bf16: True
  log_interval: 20
  eval_thresholds: [0.05, 0.1, 0.2, 0.3, 0.5]
  save_eval_attn_weights: False
  eval_every: 5000
  checkpoint_every: 5000
  ckpt_save_interval: 10000
  clipping:
    enabled: True
    max_grad_norm: 1.0
  average:
    ema:
      enabled: False
      decay: 0.99
      start: 2000
      freq: 1
      device:
    swa:
      enabled: False
      start: 100000
      freq: 100000
      device:
  compile:
    enabled: False  # Set True to wrap the full training model with torch.compile.
    fullgraph: False  # Start with False for dynamic multimodal training workloads.
    backend: inductor  # Default PyTorch compiler backend for CUDA workloads.
    mode: default  # Good starting point. Try reduce-overhead mainly for stable inference-like shapes.
    dynamic: True # Leave null for the PyTorch default. Set True only when variable shapes cause recompiles.
  gradient_checkpointing: False
optimizer:
  action:
    lr: 3e-4
    betas: [0.9, 0.95]
    weight_decay: 2e-2
  vlm:
    lr: 1e-4
    betas: [0.9, 0.95]
    weight_decay: 5e-3
  diffloss:
    lr: 5e-4
    betas: [0.9, 0.95]
    weight_decay: 1e-2
