defaults:
  - _self_ 
  - experiment: pretrain_deepspeed

name: train_egovla_deepspeed
exp_name: "deepspeed"

logging:
  project: train_egovla_deepspeed
  entity: LegendaryVLA
  resume: False
  mode: online
  name: ${now:%Y.%m.%d-%H.%M}_${name}_${hydra:runtime.choices.experiment}
  tags: ["${name}", "${hydra:runtime.choices.experiment}", "${exp_name}", "deepspeed"]
  id: null
  group: null

checkpoint:
  topk:
    monitor_key: train_loss
    mode: min
    k: 1
    format_str: 'epoch={epoch:04d}-train_loss={train_loss:.3f}.ckpt'
  save_last_ckpt: False
  save_last_snapshot: False

multi_run:
  run_dir: data/outputs/${now:%Y.%m.%d}/${now:%H.%M}_${name}_${hydra:runtime.choices.experiment}
  wandb_name_base: ${now:%Y.%m.%d-%H.%M}_${name}_${hydra:runtime.choices.experiment}

hydra:
  job:
    override_dirname: ${name}
  run:
    dir: data/outputs/${now:%Y.%m.%d}/${now:%H.%M}_${name}_${hydra:runtime.choices.experiment}
  sweep:
    dir: data/outputs/${now:%Y.%m.%d}/${now:%H.%M}_${name}_${hydra:runtime.choices.experiment}
    subdir: ${hydra.job.num}
