compute_environment: LOCAL_MACHINE
debug: false
distributed_type: FSDP
downcast_bf16: 'no'
# dynamo_config:
#   dynamo_backend: INDUCTOR
enable_cpu_affinity: false
fsdp_config:
  fsdp_version: 2
  # false here is the FSDP2 setting closest to the old SHARD_GRAD_OP behavior.
  fsdp_reshard_after_forward: False
  fsdp_auto_wrap_policy: TRANSFORMER_BASED_WRAP
  fsdp_transformer_layer_cls_to_wrap: Qwen3VLTextDecoderLayerWithKV,Qwen3VLVisionBlock,Qwen3ActionExpert,DiffLoss
  fsdp_cpu_ram_efficient_loading: true
  fsdp_state_dict_type: SHARDED_STATE_DICT
machine_rank: 0
main_process_ip: 172.18.1.150 # need to change to the main process ip
main_process_port: 12345 # need to change to the main process port
main_training_function: main
mixed_precision: bf16
num_machines: 1 # need to change to the correct number
num_processes: 8 # need to change to the correct number, sum of gpus of all nodes
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false
